#! /bin/sh

# Copyright (C)2026, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Process modifier options

if [ $# -gt 2 -a "$1" = "-git" ] ; then
  MVPREFIX="git"
  shift 1
fi

if [ $# -gt 2 -a "$1" = "-svn" ] ; then
  MVPREFIX="svn"
  shift 1
fi

ErrorExit()
{
  echo ""
  echo "Rename an Alire project directory"
  echo ""
  echo "ERROR: $1"
  echo ""
  echo "Usage: alire-rename-project [-git|-svn] <olddir> <newdir>"
  echo ""
  exit 1
}

# Validate arguments

test $# -ne 2             && ErrorExit "Incorrect number of arguments"
test ! -d "$1"            && ErrorExit "$1 is not a directory"
test -e "$2"              && ErrorExit "$2 already exists"
test ! -f "$1"/alire.toml && ErrorExit "Cannot find $1/alire.toml"

olddirname="$1"
oldprojectname=`basename "$olddirname"/*.gpr .gpr`
oldadbname="$olddirname"/src/$oldprojectname.adb
oldgprname="$olddirname"/$oldprojectname.gpr
newdirname="$2"
newprojectname=`basename "$newdirname"`
newadbname="$olddirname"/src/$newprojectname.adb
newgprname="$olddirname"/$newprojectname.gpr

find "$olddirname" -type f -exec sed -i s/$oldprojectname/$newprojectname/g {} ";"
${MVPREFIX} mv "$oldadbname" "$newadbname"
${MVPREFIX} mv "$oldgprname" "$newgprname"
${MVPREFIX} mv "$olddirname" "$newdirname"
