@ECHO OFF

REM Set the PATH environment variable for using Alire on Windows

REM Copyright (C)2021-2025, Philip Munts, President, Munts AM Corp.
REM
REM Redistribution and use in source and binary forms, with or without
REM modification, are permitted provided that the following conditions are met:
REM
REM * Redistributions of source code must retain the above copyright notice,
REM   this list of conditions and the following disclaimer.
REM
REM THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
REM AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
REM IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
REM ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
REM LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
REM CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
REM SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
REM INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
REM CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
REM ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
REM POSSIBILITY OF SUCH DAMAGE.

REM Set some environment variables

SET ALIRE_GNAT=%HOMEDRIVE%%HOMEPATH%\AppData\Local\alire\gnat
SET ALIRE_GPRBUILD=%HOMEDRIVE%%HOMEPATH%\AppData\Local\alire\gprbuild
SET ALIRE_MSYS64=%HOMEDRIVE%%HOMEPATH%\AppData\Local\alire\cache\msys64

IF "%LIBSIMPLEIO%" == "" SET LIBSIMPLEIO=C:\PROGRA~1\MuntsOS\libsimpleio
IF "%MUNTSOS%"     == "" SET MUNTSOS=C:\PROGRA~1\MuntsOS\muntsos

REM Set path

SET PATH=C:\PROGRA~1\Alire\bin;%ALIRE_GNAT%\bin;%ALIRE_GPRBUILD%\bin;%ALIRE_MSYS64%\usr\bin;%PATH%
